### ISSUE TITLE
New Twitter Updater Issue

### ISSUE THREAD

**Issue by grrttweaver** [grrttweaver/NSWN#3]
Traceback (most recent call last):
  File "NSWN_Twitter.py", line 39, in <module>
    payload = json.loads(resp.text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by gweaverKUMC** [comment]
Fixed in  [31ef3ed]
