### ISSUE TITLE
NOAA_Updater

### ISSUE THREAD

**Issue by grrttweaver** [grrttweaver/NSWN#4]
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2018.2.2\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2018.2.2\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2018.2.2\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:/Users/grrtt/Google Drive/Programming/Python/NSWN/NOAAAlerts/NOAA_Updater.py", line 38, in <module>
    if resp == 200:
  File "C:\Users\grrtt\Google Drive\Programming\Python\NSWN\venv\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\grrtt\Google Drive\Programming\Python\NSWN\venv\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\grrtt\Google Drive\Programming\Python\NSWN\venv\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\grrtt\Google Drive\Programming\Python\NSWN\venv\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\grrtt\Google Drive\Programming\Python\NSWN\venv\lib\site-packages\requests\adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.weather.gov', port=443): Max retries exceeded with url: /alerts/active (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000003EDF668>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

**Comment by grrttweaver** [comment]
Moved to jenkins to persist, this will not be an issue going forwards
