### ISSUE TITLE
Invalid or Expired Token

### ISSUE THREAD

**Issue by grrttweaver** [grrttweaver/NSWN#6]
Traceback (most recent call last):
  File "NSWN_Twitter.py", line 32, in <module>
    tweets = SevereAlerts.GetUserTimeline(config['twitter']['swx_timeline'])
  File "/Library/Python/2.7/site-packages/twitter/api.py", line 809, in GetUserTimeline
    resp = self._RequestUrl(url, 'GET', data=parameters)
  File "/Library/Python/2.7/site-packages/twitter/api.py", line 4944, in _RequestUrl
    limit = self.CheckRateLimit(url)
  File "/Library/Python/2.7/site-packages/twitter/api.py", line 4791, in CheckRateLimit
    self.InitializeRateLimit()
  File "/Library/Python/2.7/site-packages/twitter/api.py", line 4774, in InitializeRateLimit
    data = self._ParseAndCheckTwitter(resp.content.decode('utf-8'))
  File "/Library/Python/2.7/site-packages/twitter/api.py", line 4890, in _ParseAndCheckTwitter
    self._CheckForTwitterError(data)
  File "/Library/Python/2.7/site-packages/twitter/api.py", line 4910, in _CheckForTwitterError
    raise TwitterError(data['errors'])
twitter.error.TwitterError: [{u'message': u'Invalid or expired token.', u'code': 89}]

**Comment by grrttweaver** [comment]
Token expired. Regenerated new token

apps.twitter.com
